# Local Redis on a conflict-free host port 6380
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"          # host:container
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  redisdata:
